//base
LUA_BIND_VOID(wait, (LUA_ARG_INT));

// control
LUA_PUSH_INT(CONTROL_COUNT);
LUA_PUSH_INT(CONTROL_UP);
LUA_PUSH_INT(CONTROL_RIGHT);
LUA_PUSH_INT(CONTROL_DOWN);
LUA_PUSH_INT(CONTROL_LEFT);
LUA_PUSH_INT(CONTROL_ENTER);
LUA_PUSH_INT(CONTROL_ESC);

LUA_BIND_RETR(control_getState, (LUA_ARG_INT), LUA_RET_BOOL);